export const ROLES = Object.freeze({
  SUPER_ADMIN: 'super-admin', ADMIN: 'admin', SUPERVISOR: 'supervisor',
  HEADTEACHER: 'headteacher', HOD: 'hod', DIRECTOR_OF_STUDIES: 'director-of-studies',
  DEPUTY_HEAD: 'deputy-head', BURSAR: 'bursar', INVENTORY_MANAGER: 'inventory-manager',
  REGISTRAR: 'registrar', ACADEMIC_ADMIN: 'academic-admin', CLASS_TEACHER: 'class-teacher',
  TEACHER: 'teacher', STUDENT: 'student', PARENT: 'parent',
});

const staff = [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.DEPUTY_HEAD, ROLES.BURSAR, ROLES.INVENTORY_MANAGER, ROLES.REGISTRAR, ROLES.ACADEMIC_ADMIN, ROLES.CLASS_TEACHER, ROLES.TEACHER];
const academicStaff = [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.DEPUTY_HEAD, ROLES.HOD, ROLES.ACADEMIC_ADMIN, ROLES.CLASS_TEACHER, ROLES.TEACHER];
const directorStudiesAccess = [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.DEPUTY_HEAD, ROLES.HOD, ROLES.ACADEMIC_ADMIN, ROLES.DIRECTOR_OF_STUDIES];

export const TAB_ACCESS = Object.freeze({
  dashboard: [...directorStudiesAccess, ROLES.BURSAR, ROLES.REGISTRAR, ROLES.INVENTORY_MANAGER, ROLES.TEACHER, ROLES.STUDENT, ROLES.PARENT],
  parent_portal: [ROLES.PARENT],
  admissions: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.REGISTRAR],
  students: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.REGISTRAR, ROLES.SUPERVISOR, ROLES.DEPUTY_HEAD, ROLES.ACADEMIC_ADMIN, ROLES.DIRECTOR_OF_STUDIES, ROLES.CLASS_TEACHER, ROLES.TEACHER],
  teachers: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.DEPUTY_HEAD, ROLES.ACADEMIC_ADMIN, ROLES.DIRECTOR_OF_STUDIES],
  hr: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  classes: [...directorStudiesAccess, ROLES.CLASS_TEACHER, ROLES.TEACHER],
  attendance: [...directorStudiesAccess, ROLES.CLASS_TEACHER, ROLES.TEACHER],
  grades: [...directorStudiesAccess, ROLES.STUDENT, ROLES.PARENT],
  fees: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.BURSAR, ROLES.STUDENT, ROLES.PARENT],
  finance: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.BURSAR],
  hostel: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.DEPUTY_HEAD, ROLES.CLASS_TEACHER, ROLES.TEACHER, ROLES.PARENT],
  library: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.TEACHER, ROLES.CLASS_TEACHER],
  inventory: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.INVENTORY_MANAGER],
  operations: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.DEPUTY_HEAD, ROLES.TEACHER, ROLES.CLASS_TEACHER],
  messages: [...staff, ROLES.PARENT, ROLES.HOD, ROLES.DIRECTOR_OF_STUDIES],
  lms: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HOD, ROLES.ACADEMIC_ADMIN, ROLES.DIRECTOR_OF_STUDIES, ROLES.TEACHER, ROLES.CLASS_TEACHER, ROLES.STUDENT],
  reports: [...directorStudiesAccess, ROLES.STUDENT, ROLES.PARENT],
  analytics: [...directorStudiesAccess],
  settings: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  notifications: [...staff, ROLES.STUDENT, ROLES.PARENT, ROLES.DIRECTOR_OF_STUDIES],
});

const inheritedRole = (role) => ({ [ROLES.HEADTEACHER]: ROLES.ADMIN, [ROLES.HOD]: ROLES.ACADEMIC_ADMIN, [ROLES.DIRECTOR_OF_STUDIES]: ROLES.ACADEMIC_ADMIN }[role] || role);
export const canAccessTab = (role, tab) => (TAB_ACCESS[tab] || []).includes(inheritedRole(role));
