server.port=5000

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/uganda-school-system

# JWT settings (custom properties)
jwt.secret=supersecretjwtkeyforugandaschoolsystem2026
jwt.expirationMs=86400000
